### ISSUE TITLE
Build error on OSX, Node 4.2.1

### ISSUE THREAD

**Issue by darobin** [rimmartin/saxon-node#12]
I am trying to set it up but getting build errors (I don't particularly want to build it, but apparently not finding a pre-build). Here is the output:

```
 hypatia [18:51] rdfa-worker (katex) $ export SAXON_HOME=/Projects/SA/Saxon-HEC-v0.3.1.1-Mac-native/
 hypatia [18:51] rdfa-worker (katex) $ export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/
 hypatia [18:51] rdfa-worker (katex) $ npm install --save saxon-node
\
> saxon-node@0.1.0 install /Projects/SA/rdfa-worker/node_modules/saxon-node
> node-pre-gyp install --fallback-to-build

  CXX(target) Release/obj.target/saxonXslt/src/SaxonProcessor.o
clang: warning: -O4 is equivalent to -O3
In file included from ../src/SaxonProcessor.cpp:9:
../src/SaxonProcessor.h:207:10: warning: implicit conversion of NULL constant to 'bool' [-Wnull-conversion]
                return NULL;
                ~~~~~~ ^~~~
                       false
In file included from ../src/SaxonProcessor.cpp:12:
../src/XdmValue.cpp:114:14: warning: adding 'int' to a string does not append to the string [-Wstring-plus-int]
                                return ""+valueInt;
                                       ~~^~~~~~~~~
../src/XdmValue.cpp:114:14: note: use array indexing to silence this warning
                                return ""+valueInt;
                                         ^
                                       & [        ]
../src/XdmValue.cpp:145:11: warning: unused variable 'env' [-Wunused-variable]
                JNIEnv *env = p->env;
                        ^
../src/SaxonProcessor.cpp:161:13: warning: unused variable 'obj' [-Wunused-variable]
    jobject obj;
            ^
../src/SaxonProcessor.cpp:160:25: warning: unused variable 'mID' [-Wunused-variable]
    jmethodID MID_init, mID;
                        ^
../src/SaxonProcessor.cpp:174:25: warning: unused variable 'mID' [-Wunused-variable]
    jmethodID MID_init, mID;
                        ^
../src/SaxonProcessor.cpp:193:25: warning: unused variable 'mID' [-Wunused-variable]
    jmethodID MID_init, mID;
                        ^
7 warnings generated.
  CXX(target) Release/obj.target/saxonXslt/src/SaxonProcessorJS.o
clang: warning: -O4 is equivalent to -O3
In file included from ../src/SaxonProcessorJS.cxx:7:
In file included from ../src/SaxonProcessorJS.hpp:12:
../src/SaxonProcessor.h:207:10: warning: implicit conversion of NULL constant to 'bool' [-Wnull-conversion]
                return NULL;
                ~~~~~~ ^~~~
                       false
In file included from ../src/SaxonProcessorJS.cxx:7:
../src/SaxonProcessorJS.hpp:27:14: error: no type named 'shared_ptr' in namespace 'std'
        std::shared_ptr<SaxonProcessor> processor;
        ~~~~~^
../src/SaxonProcessorJS.hpp:27:24: error: expected member name or ';' after declaration specifiers
        std::shared_ptr<SaxonProcessor> processor;
        ~~~~~~~~~~~~~~~^
../src/SaxonProcessorJS.hpp:60:45: error: member initializer 'processor' does not name a non-static data member or base class
        SaxonProcessorJS(bool l) : cwd(""), processor (new SaxonProcessor(false)) {
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/SaxonProcessorJS.hpp:127:21: error: no member named 'processor' in 'saxon_node::SaxonProcessorJS'
                sp->processor->setcwd((*cwd));
                ~~  ^
../src/SaxonProcessorJS.hpp:137:21: error: no member named 'processor' in 'saxon_node::SaxonProcessorJS'
                sp->processor->setResourcesDirectory((*resourcesDirectory));
                ~~  ^
../src/SaxonProcessorJS.hpp:144:40: error: no member named 'processor' in 'saxon_node::SaxonProcessorJS'
                const char* buffer=sp->processor->version();
                                   ~~  ^
In file included from ../src/SaxonProcessorJS.cxx:8:
../src/XsltProcessorJS.hpp:398:14: error: no type named 'shared_ptr' in namespace 'std'
        std::shared_ptr<XsltProcessor> xsltProcessor;
        ~~~~~^
../src/XsltProcessorJS.hpp:398:24: error: expected member name or ';' after declaration specifiers
        std::shared_ptr<XsltProcessor> xsltProcessor;
        ~~~~~~~~~~~~~~~^
../src/XsltProcessorJS.hpp:90:47: error: no member named 'processor' in 'saxon_node::SaxonProcessorJS'
            xp->xsltProcessor.reset(xp->proc->processor->newTransformer());
                                    ~~~~~~~~  ^
../src/XsltProcessorJS.hpp:90:17: error: no member named 'xsltProcessor' in 'saxon_node::XsltProcessorJS'
            xp->xsltProcessor.reset(xp->proc->processor->newTransformer());
            ~~  ^
../src/XsltProcessorJS.hpp:167:21: error: no member named 'xsltProcessor' in 'saxon_node::XsltProcessorJS'
                xp->xsltProcessor->setParameter(*pn, new XdmValue(*pnValue));
                ~~  ^
../src/XsltProcessorJS.hpp:173:17: error: no member named 'xsltProcessor' in 'saxon_node::XsltProcessorJS'
            xp->xsltProcessor->xsltSaveResultToFile((*sourceFile), (*stylesheetfile), (*outputfile));
            ~~  ^
../src/XsltProcessorJS.hpp:197:33: error: no member named 'xsltProcessor' in 'saxon_node::XsltProcessorJS'
                            xp->xsltProcessor->setParameter(*pn, new XdmValue(*pnValue));
                            ~~  ^
../src/XsltProcessorJS.hpp:201:48: error: no member named 'xsltProcessor' in 'saxon_node::XsltProcessorJS'
                        const char* buffer=xp->xsltProcessor->xsltApplyStylesheet((*source), NULL);
                                           ~~  ^
../src/XsltProcessorJS.hpp:203:32: error: no member named 'xsltProcessor' in 'saxon_node::XsltProcessorJS'
                        if(xp->xsltProcessor->exceptionOccurred() || xp->xsltProcessor->exceptionCount()>0){
                           ~~  ^
../src/XsltProcessorJS.hpp:203:74: error: no member named 'xsltProcessor' in 'saxon_node::XsltProcessorJS'
                        if(xp->xsltProcessor->exceptionOccurred() || xp->xsltProcessor->exceptionCount()>0){
                                                                     ~~  ^
../src/XsltProcessorJS.hpp:204:67: error: no member named 'to_string' in namespace 'std'
                            std::string errorMessage="# of "+std::to_string(xp->xsltProcessor->exceptionCount());
                                                             ~~~~~^
../src/XsltProcessorJS.hpp:204:81: error: no member named 'xsltProcessor' in 'saxon_node::XsltProcessorJS'
                            std::string errorMessage="# of "+std::to_string(xp->xsltProcessor->exceptionCount());
                                                                            ~~  ^
../src/XsltProcessorJS.hpp:228:33: error: no member named 'xsltProcessor' in 'saxon_node::XsltProcessorJS'
                            xp->xsltProcessor->setParameter(*pn, new XdmValue(*pnValue));
                            ~~  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.
make: *** [Release/obj.target/saxonXslt/src/SaxonProcessorJS.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/robin/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "/Users/robin/.nvm/versions/node/v4.2.1/bin/node" "/Users/robin/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Projects/SA/rdfa-worker/node_modules/saxon-node/lib/binding/saxonXslt.node" "--module_name=saxonXslt" "--module_path=/Projects/SA/rdfa-worker/node_modules/saxon-node/lib/binding"
gyp ERR! cwd /Projects/SA/rdfa-worker/node_modules/saxon-node
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/robin/.nvm/versions/node/v4.2.1/bin/node /Users/robin/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Projects/SA/rdfa-worker/node_modules/saxon-node/lib/binding/saxonXslt.node --module_name=saxonXslt --module_path=/Projects/SA/rdfa-worker/node_modules/saxon-node/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Projects/SA/rdfa-worker/node_modules/saxon-node/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Darwin 14.4.0
node-pre-gyp ERR! command "/Users/robin/.nvm/versions/node/v4.2.1/bin/node" "/Projects/SA/rdfa-worker/node_modules/saxon-node/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Projects/SA/rdfa-worker/node_modules/saxon-node
node-pre-gyp ERR! node -v v4.2.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.8
node-pre-gyp ERR! not ok 
Failed to execute '/Users/robin/.nvm/versions/node/v4.2.1/bin/node /Users/robin/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Projects/SA/rdfa-worker/node_modules/saxon-node/lib/binding/saxonXslt.node --module_name=saxonXslt --module_path=/Projects/SA/rdfa-worker/node_modules/saxon-node/lib/binding' (1)
npm ERR! Darwin 14.4.0
npm ERR! argv "/Users/robin/.nvm/versions/node/v4.2.1/bin/node" "/Users/robin/.nvm/versions/node/v4.2.1/bin/npm" "install" "--save" "saxon-node"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! saxon-node@0.1.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the saxon-node@0.1.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the saxon-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls saxon-node
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Projects/SA/rdfa-worker/npm-debug.log
```

I am not much of a C++ developer so I am not sure how best to report this; if there is any information I can usefully provide please let me know.

PS: I saw the thread asking if there would be interest in this, to us it would be very useful!

**Comment by rimmartin** [comment]
Hi,
your version of g++?  Should be at least 4.9.

See discussion about using homebrew if you need to upgrade your compiler
https://github.com/ryancole/hdf5.node/issues/4

I'll get my sys admin to install v4.2.1 for me and make some prebuilts for this project

**Comment by darobin** [comment]
Ah, I have g++ 4.9 installed but it wasn't picking it up properly, and that was the problem. Adding `export CXX=/usr/local/bin/g++-4.9` makes it build!

Unfortunately I can't get it to run yet; it's looking for `libsaxon.dll` instead of `dyib`.

**Comment by rimmartin** [comment]
I'll test this evening

**Comment by rimmartin** [comment]
Hoping my sysadmin will add v4.2.1 for me to test. It's the only mac I have access to

**Comment by rimmartin** [comment]
My sysadmin installed and I built and ran for 4.2.1.

By sure your DYL_LIBRARY_PATH has the jet jvm first.  See the readme page
