### ISSUE TITLE
Access Denied when running npm install

### ISSUE THREAD

**Issue by mhchristensen** [rimmartin/saxon-node#4]
Hi @rimmartin ,

I was hoping you could give some assistance with installing on my mac.  Basically 2 questions.
1. Do you know why I'm getting a 403 from AWS?  It seems it might react differently if the prebuilt wasn't available for mac.  
2. If there isn't a prebuilt for mac os x yosemite.  Is that something you could provide?  It seems my machine is really having trouble installing

Here's the full output when I run:
npm install saxon-node --fallback-to-build
# 

```
Michaels-MacBook-Pro:validator michaelchristensen$ which java
/usr/bin/java
Michaels-MacBook-Pro:validator michaelchristensen$ /usr/libexec/java_home -v 1.7
/Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home
Michaels-MacBook-Pro:validator michaelchristensen$ export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home
Michaels-MacBook-Pro:validator michaelchristensen$ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home
Michaels-MacBook-Pro:validator michaelchristensen$ npm install saxon-node --fallback-to-build
npm http GET https://registry.npmjs.org/saxon-node
npm http 304 https://registry.npmjs.org/saxon-node

> saxon-node@0.0.5 install /Users/michaelchristensen/SourceCode/lantana/validator/node_modules/saxon-node
> node-pre-gyp install --fallback-to-build

node-pre-gyp http GET https://saxon-node.s3-us-west-2.amazonaws.com/v0.0.5/saxonXslt-v0.0.5-node-v11-darwin-x64.tar.gz
node-pre-gyp http 403 https://saxon-node.s3-us-west-2.amazonaws.com/v0.0.5/saxonXslt-v0.0.5-node-v11-darwin-x64.tar.gz
node-pre-gyp http 403 status code downloading tarball https://saxon-node.s3-us-west-2.amazonaws.com/v0.0.5/saxonXslt-v0.0.5-node-v11-darwin-x64.tar.gz (falling back to source compile with node-gyp) 
  CXX(target) Release/obj.target/saxonXslt/src/SaxonProcessor.o
clang: warning: -O4 is equivalent to -O3
In file included from ../src/SaxonProcessor.cpp:9:
../src/SaxonProcessor.h:207:10: warning: implicit conversion of NULL constant to 'bool' [-Wnull-conversion]
                return NULL;
                ~~~~~~ ^~~~
                       false
In file included from ../src/SaxonProcessor.cpp:12:
../src/XdmValue.cpp:114:14: warning: adding 'int' to a string does not append to the string [-Wstring-plus-int]
                                return ""+valueInt;
                                       ~~^~~~~~~~~
../src/XdmValue.cpp:114:14: note: use array indexing to silence this warning
                                return ""+valueInt;
                                         ^
                                       & [        ]
../src/XdmValue.cpp:145:11: warning: unused variable 'env' [-Wunused-variable]
                JNIEnv *env = p->env;
                        ^
../src/SaxonProcessor.cpp:161:13: warning: unused variable 'obj' [-Wunused-variable]
    jobject obj;
            ^
../src/SaxonProcessor.cpp:160:25: warning: unused variable 'mID' [-Wunused-variable]
    jmethodID MID_init, mID;
                        ^
../src/SaxonProcessor.cpp:174:25: warning: unused variable 'mID' [-Wunused-variable]
    jmethodID MID_init, mID;
                        ^
../src/SaxonProcessor.cpp:193:25: warning: unused variable 'mID' [-Wunused-variable]
    jmethodID MID_init, mID;
                        ^
7 warnings generated.
  CXX(target) Release/obj.target/saxonXslt/src/SaxonProcessorJS.o
clang: warning: -O4 is equivalent to -O3
In file included from ../src/SaxonProcessorJS.cxx:7:
In file included from ../src/SaxonProcessorJS.hpp:12:
../src/SaxonProcessor.h:207:10: warning: implicit conversion of NULL constant to 'bool' [-Wnull-conversion]
                return NULL;
                ~~~~~~ ^~~~
                       false
In file included from ../src/SaxonProcessorJS.cxx:7:
../src/SaxonProcessorJS.hpp:27:14: error: no type named 'shared_ptr' in namespace 'std'
        std::shared_ptr<SaxonProcessor> processor;
        ~~~~~^
../src/SaxonProcessorJS.hpp:27:24: error: expected member name or ';' after declaration specifiers
        std::shared_ptr<SaxonProcessor> processor;
        ~~~~~~~~~~~~~~~^
../src/SaxonProcessorJS.hpp:69:35: error: no type named 'FunctionCallbackInfo' in namespace 'v8'
        static void New(const v8::FunctionCallbackInfo<Value>& args) {
                              ~~~~^
../src/SaxonProcessorJS.hpp:69:55: error: expected ')'
        static void New(const v8::FunctionCallbackInfo<Value>& args) {
                                                      ^
../src/SaxonProcessorJS.hpp:69:24: note: to match this '('
        static void New(const v8::FunctionCallbackInfo<Value>& args) {
                       ^
../src/SaxonProcessorJS.hpp:88:46: error: no type named 'FunctionCallbackInfo' in namespace 'v8'
        static void newTransformer(const v8::FunctionCallbackInfo<Value>& args);
                                         ~~~~^
../src/SaxonProcessorJS.hpp:88:66: error: expected ')'
        static void newTransformer(const v8::FunctionCallbackInfo<Value>& args);
                                                                 ^
../src/SaxonProcessorJS.hpp:88:35: note: to match this '('
        static void newTransformer(const v8::FunctionCallbackInfo<Value>& args);
                                  ^
../src/SaxonProcessorJS.hpp:90:50: error: no type named 'FunctionCallbackInfo' in namespace 'v8'
        static void newXQueryProcessor(const v8::FunctionCallbackInfo<Value>& args);
                                             ~~~~^
../src/SaxonProcessorJS.hpp:90:70: error: expected ')'
        static void newXQueryProcessor(const v8::FunctionCallbackInfo<Value>& args);
                                                                     ^
../src/SaxonProcessorJS.hpp:90:39: note: to match this '('
        static void newXQueryProcessor(const v8::FunctionCallbackInfo<Value>& args);
                                      ^
../src/SaxonProcessorJS.hpp:92:41: error: no type named 'FunctionCallbackInfo' in namespace 'v8'
        static void parseFile(const v8::FunctionCallbackInfo<Value>& args) {
                                    ~~~~^
../src/SaxonProcessorJS.hpp:92:61: error: expected ')'
        static void parseFile(const v8::FunctionCallbackInfo<Value>& args) {
                                                            ^
../src/SaxonProcessorJS.hpp:92:30: note: to match this '('
        static void parseFile(const v8::FunctionCallbackInfo<Value>& args) {
                             ^
../src/SaxonProcessorJS.hpp:97:40: error: no type named 'FunctionCallbackInfo' in namespace 'v8'
        static void parseURI(const v8::FunctionCallbackInfo<Value>& args) {
                                   ~~~~^
../src/SaxonProcessorJS.hpp:97:60: error: expected ')'
        static void parseURI(const v8::FunctionCallbackInfo<Value>& args) {
                                                           ^
../src/SaxonProcessorJS.hpp:97:29: note: to match this '('
        static void parseURI(const v8::FunctionCallbackInfo<Value>& args) {
                            ^
../src/SaxonProcessorJS.hpp:102:46: error: no type named 'FunctionCallbackInfo' in namespace 'v8'
        static void setSourceValue(const v8::FunctionCallbackInfo<Value>& args) {
                                         ~~~~^
../src/SaxonProcessorJS.hpp:102:66: error: expected ')'
        static void setSourceValue(const v8::FunctionCallbackInfo<Value>& args) {
                                                                 ^
../src/SaxonProcessorJS.hpp:102:35: note: to match this '('
        static void setSourceValue(const v8::FunctionCallbackInfo<Value>& args) {
                                  ^
../src/SaxonProcessorJS.hpp:107:45: error: no type named 'FunctionCallbackInfo' in namespace 'v8'
        static void setSourceFile(const v8::FunctionCallbackInfo<Value>& args) {
                                        ~~~~^
../src/SaxonProcessorJS.hpp:107:65: error: expected ')'
        static void setSourceFile(const v8::FunctionCallbackInfo<Value>& args) {
                                                                ^
../src/SaxonProcessorJS.hpp:107:34: note: to match this '('
        static void setSourceFile(const v8::FunctionCallbackInfo<Value>& args) {
                                 ^
../src/SaxonProcessorJS.hpp:112:43: error: no type named 'FunctionCallbackInfo' in namespace 'v8'
        static void setProperty(const v8::FunctionCallbackInfo<Value>& args) {
                                      ~~~~^
../src/SaxonProcessorJS.hpp:112:63: error: expected ')'
        static void setProperty(const v8::FunctionCallbackInfo<Value>& args) {
                                                              ^
../src/SaxonProcessorJS.hpp:112:32: note: to match this '('
        static void setProperty(const v8::FunctionCallbackInfo<Value>& args) {
                               ^
../src/SaxonProcessorJS.hpp:117:45: error: no type named 'FunctionCallbackInfo' in namespace 'v8'
        static void getProperties(const v8::FunctionCallbackInfo<Value>& args) {
                                        ~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.
make: *** [Release/obj.target/saxonXslt/src/SaxonProcessorJS.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/michaelchristensen/SourceCode/lantana/validator/node_modules/saxon-node/lib/binding/saxonXslt.node" "--module_name=saxonXslt" "--module_path=/Users/michaelchristensen/SourceCode/lantana/validator/node_modules/saxon-node/lib/binding"
gyp ERR! cwd /Users/michaelchristensen/SourceCode/lantana/validator/node_modules/saxon-node
gyp ERR! node -v v0.10.24
gyp ERR! node-gyp -v v0.12.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/michaelchristensen/SourceCode/lantana/validator/node_modules/saxon-node/lib/binding/saxonXslt.node --module_name=saxonXslt --module_path=/Users/michaelchristensen/SourceCode/lantana/validator/node_modules/saxon-node/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/michaelchristensen/SourceCode/lantana/validator/node_modules/saxon-node/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:735:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:802:5)
node-pre-gyp ERR! System Darwin 14.3.0
node-pre-gyp ERR! command "node" "/Users/michaelchristensen/SourceCode/lantana/validator/node_modules/saxon-node/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/michaelchristensen/SourceCode/lantana/validator/node_modules/saxon-node
node-pre-gyp ERR! node -v v0.10.24
node-pre-gyp ERR! node-pre-gyp -v v0.6.8
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/michaelchristensen/SourceCode/lantana/validator/node_modules/saxon-node/lib/binding/saxonXslt.node --module_name=saxonXslt --module_path=/Users/michaelchristensen/SourceCode/lantana/validator/node_modules/saxon-node/lib/binding' (1)
npm ERR! saxon-node@0.0.5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the saxon-node@0.0.5 install script.
npm ERR! This is most likely a problem with the saxon-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls saxon-node
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 14.3.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "saxon-node" "--fallback-to-build"
npm ERR! cwd /Users/michaelchristensen/SourceCode/lantana/validator
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/michaelchristensen/SourceCode/lantana/validator/npm-debug.log
npm ERR! not ok code 0
Michaels-MacBook-Pro:validator michaelchristensen$ 
```

**Comment by mhchristensen** [comment]
Some added info I think it might because the compiler used by mac

Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix

**Comment by mhchristensen** [comment]
Did finally get it to compile by modifying the bindings file but at runtime I get this error:
libsaxon.dylib doesn't contain public JNI_GetDefaultJavaVMInitArgs

**Comment by rimmartin** [comment]
Current prebuilt on mac is for nodejs v0.11.x.  I'm getting my sys admin to upgrade to nodejs at work so I can build for v 0.12.x.  And I'm trying to borrow a newer mac for more mac prebuilts

if you build before I get the prebuilt you'll need gcc 4.9 at least. https://github.com/ryancole/hdf5.node/issues/4 where homebrew is involved.  Your first error was the compiler it was picking up wasn't at c++11 standard and an older nodejs.

The 
```
libsaxon.dylib doesn't contain public JNI_GetDefaultJavaVMInitArgs
```
error when it happens on other machines the build of saxon-node and java aren't of the same bit; one is 32 and the other is 64

**Comment by rimmartin** [comment]
there is also the command switch
```
npm install --build-from-source
```
which skips looking at AWS

**Comment by seanmcilvenna** [comment]
hey rimmartin... I'm getting 403 whenever I try to access your s3 builds. Is something configured incorrectly at your s3 account?

**Comment by rimmartin** [comment]
I'll look...

**Comment by rimmartin** [comment]
Put a s3:getObject bucket policy for principals  * on it. Went by an aws example

**Comment by seanmcilvenna** [comment]
Still getting 403:

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>6AC23F50E16FFD0F</RequestId>
<HostId>
Ya+X/GpVZqtDiTiawWu3s8M0WHUfr6omc4f65WFuzIsdIqWJ2RWUlM4y1rijEAifrKH9xfe5w9s=
</HostId>
</Error>
```

From the following URL:
https://saxon-node.s3-us-west-2.amazonaws.com/v0.0.5/saxonXslt-v0.0.5-node-v11-darwin-x64.tar.gz

**Comment by rimmartin** [comment]
I used a different user than my s3 and it pulled with npm for nodejs v 0.11.x.

Not sure yet but it might return a 403 when versions don't match

you are using 
```
npm install saxon-node --fallback-to-build
```
?
nodejs v 0.12.x?

**Comment by mhchristensen** [comment]
On Mac I was using v0.10.x and then upgraded to 0.12.x with fixed some compile issues.  With modifying the cflags in the bindings I was able to get it to compile on mac.

On windows I'm getting a very similar error to what I had before on mac:

libsaxon.dll doesn't contain public JNI_GetDefaultJavaVMInitArgs

Above you mentioned that's because of a 32bit application trying to talk to 64 bit java. 
Just to double check here, is JAVA a runtime dependency for this library to work, or is it just required to compile?

**Comment by rimmartin** [comment]
only the jni.h and the OS specific header.  No runtime dependency.  The Excelsior Jet rt is with the saxon package and is the runtime.  They just don't ship the java headers

**Comment by rimmartin** [comment]
on mac I've only built with v0.11.  trying to get an upgrade to v0.12 on there by sys admin and then publish

**Comment by rimmartin** [comment]
on windows the saxon package is only 32 bit at this time

**Comment by mhchristensen** [comment]
I downgraded my node to 0.11.16  and now it correctly installs with npm install saxon-node.  It appeared to pull the binaries and succeed without manual build.

However I still get this error on startup:
```
"C:\Program Files (x86)\JetBrains\WebStorm 10.0.4\bin\runnerw.exe" "C:\Users\Michael Christensen\AppData\Roaming\nvm\v0.11.16\node.exe" --debug-brk=34773 --nolazy server.js
Debugger listening on port 34773
[Error: %1 is not a valid Win32 application.
```

And at runtime when I try to instantiater a SaxonProcessor:
```
Unable to load 
libsaxon.dll doesn't contain public JNI_GetDefaultJavaVMInitArgs
```
if I debug while the code is running and execute:

     process.env.JAVA_HOME

I get

     C:\Program Files (x86)\Java\jdk1.8.0_51

Which is the 32 bit jdk I have installed.

At this point as far as I can tell I'm running the same node major version as you, using the 32bit binaries pulled down from AWS and using 32 bit Java.  Any ideas?

**Comment by mhchristensen** [comment]
Heres the complete output of what appears to be a successful install (but still fails at runtime)

```
E:\ChristensenSolutions\SourceCode\Lantana\validator>npm install saxon-node --fallback-to-build
/
> saxon-node@0.0.5 install E:\ChristensenSolutions\SourceCode\Lantana\validator\node_modules\saxon-node
> node-pre-gyp install --fallback-to-build


E:\ChristensenSolutions\SourceCode\Lantana\validator\node_modules\saxon-node>node "C:\Users\MICHAE~1\AppData\Roaming\nvm\v0.11.16\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean

E:\ChristensenSolutions\SourceCode\Lantana\validator\node_modules\saxon-node>node "C:\Users\MICHAE~1\AppData\Roaming\nvm\v0.11.16\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=E:\ChristensenSo
lutions\SourceCode\Lantana\validator\node_modules\saxon-node\lib\binding\saxonXslt.node --module_name=saxonXslt --module_path=E:\ChristensenSolutions\SourceCode\Lantana\validator\node_modules\saxon-node\lib\binding
child_process: customFds option is deprecated, use stdio instead.

E:\ChristensenSolutions\SourceCode\Lantana\validator\node_modules\saxon-node>node "C:\Users\MICHAE~1\AppData\Roaming\nvm\v0.11.16\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" build --fallback-to-build --module=E:\ChristensenSoluti
ons\SourceCode\Lantana\validator\node_modules\saxon-node\lib\binding\saxonXslt.node --module_name=saxonXslt --module_path=E:\ChristensenSolutions\SourceCode\Lantana\validator\node_modules\saxon-node\lib\binding
child_process: customFds option is deprecated, use stdio instead.
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  SaxonProcessor.cpp
  SaxonProcessorJS.cxx
  saxonXslt.cxx
..\src\SaxonProcessor.cpp(160): warning C4101: 'mID' : unreferenced local variable [E:\ChristensenSolutions\SourceCode\Lantana\validator\node_modules\saxon-node\build\saxonXslt.vcxproj]
..\src\SaxonProcessor.cpp(161): warning C4101: 'obj' : unreferenced local variable [E:\ChristensenSolutions\SourceCode\Lantana\validator\node_modules\saxon-node\build\saxonXslt.vcxproj]
..\src\SaxonProcessor.cpp(174): warning C4101: 'mID' : unreferenced local variable [E:\ChristensenSolutions\SourceCode\Lantana\validator\node_modules\saxon-node\build\saxonXslt.vcxproj]
..\src\SaxonProcessor.cpp(193): warning C4101: 'mID' : unreferenced local variable [E:\ChristensenSolutions\SourceCode\Lantana\validator\node_modules\saxon-node\build\saxonXslt.vcxproj]
     Creating library E:\ChristensenSolutions\SourceCode\Lantana\validator\node_modules\saxon-node\build\Release\saxonXslt.lib and object E:\ChristensenSolutions\SourceCode\Lantana\validator\node_modules\saxon-node\build\Release\saxonXslt.exp
  Generating code
  Finished generating code
  saxonXslt.vcxproj -> E:\ChristensenSolutions\SourceCode\Lantana\validator\node_modules\saxon-node\build\Release\\saxonXslt.node
  Copying E:\ChristensenSolutions\SourceCode\Lantana\validator\node_modules\saxon-node\build\Release\/saxonXslt.node to E:/ChristensenSolutions/SourceCode/Lantana/validator/node_modules/saxon-node/lib/binding\saxonXslt.node
          1 file(s) copied.
saxon-node@0.0.5 node_modules\saxon-node

E:\ChristensenSolutions\SourceCode\Lantana\validator>
```

This time it doesn't look like it attempted to download from AWS?

**Comment by rimmartin** [comment]
On windows/linux I'm at v0.12.x; all v0.12.x show in S3 as saxonXslt-v0.0.5-node-v14-xxxxx

Only on mac did I build with v0.11.x; want to upgrade but don't have permissions on a work machine to do it myself

On windows
```
[Error: %1 is not a valid Win32 application.
```
means the nodejs is 64 bit; but saxon/C is 32 bit only on windows and my prebuilt is only 32 bit http://www.saxonica.com/html/saxon-c/index.html

Your last output did fall back to building successfully; probably built 64 bit saxon-node glue. Probable error is
```
dllName: C:\Software\Saxonica\SaxonHEC0.3.1/libsaxon.dll
Unable to load C:\Software\Saxonica\SaxonHEC0.3.1/libsaxon.dll
libsaxon.dll doesn't contain public JNI_GetDefaultJavaVMInitArgs
```

**Comment by rimmartin** [comment]
Also when running you'll need to set/export
```
set SAXON_HOME=C:\Software\Saxonica\SaxonHEC0.3.1
```
set it to the directory where the libsaxon.xxx is installed

**Comment by mhchristensen** [comment]
Thanks that was helpful.  I switched my windows environment to 32 bit node 0.12.7  away from 0.11.16 32 bit.  

I also put the SAXON_HOME in the path before running node.  I was under the impression that setting SAXON_HOME was only needed during install.    I'm not sure which of those two things fixed it but It's working now. Thanks!

**Comment by rimmartin** [comment]
good! needed both.

The saxon library isn't linked at compile/build time;  it is dynamically loaded at run time and it in turn kicks up the  Excelsior JET's runtime to run the converted xslt engine.

I made it depend on SAXON_HOME so saxon/C package can be installed where the users chooses.

I should get a mac v0.12.7 prebuilt going over the wekend

**Comment by mhchristensen** [comment]
Thanks @rimmartin,

So if I understand correctly, JAVA isn't actually required to be installed at runtime?  We're using HEC, so our understanding it its using native C/C++ code.

**Comment by rimmartin** [comment]
Right, java is not used at runtime.  And during compile only those jni headers are used.  The JET binaries implement for those headers; I guess legally they didn't want to ship the headers.
Under C:\Software\Saxonica\SaxonHEC0.3.1\rt\bin\jetvm you'll find a jvm.dll which is the interface into the running of the java-compiled-to-native libsaxon.dll (No longer byte code). The compile to native was done by Saxonica with Excelsior.  What is released under SaxonHEC0.3.1 has a Mozilla Public License version 2.0.  Some of the SaxonHEC0.3.1 API source I copied into saxon-node because of some changes I was making with the environment variables locating saxon.  Eventually my changes will get rolled back into Saxon/C API or replaced with better in future releases. 

If I get the prebuilts satisfying then users won't need the java headers at all and only need the saxon dll/so/dylib and the rt folders of SaxonHEC0.x.x

**Comment by rimmartin** [comment]
from my c++ projects it appears the libsaxon.dll knows the relative path into rt
